/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'STM32F405RG' 
 * Target:  'STM32F405RG' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* Keil::Compiler&ARM Compiler:I/O:STDOUT&User@1.2.0 */
#define RTE_Compiler_IO_STDOUT          /* Compiler I/O: STDOUT */
#define RTE_Compiler_IO_STDOUT_User     /* Compiler I/O: STDOUT User */


#endif /* RTE_COMPONENTS_H */
